build:
  image: node:6
  environment:
    - NPM_CONFIG_LOGLEVEL=warn
  commands:
    - "npm install"
    - "npm install buildgoggles@0.2.0-3"
    - "./node_modules/buildgoggles/bin/buildgoggles --releaseOwner=ferhimedamine --releaseBranch=master"

cache:
  mount:
    - node_modules
    - .git
        
